import React from 'react'

const Post = () => {
  return (
    <div className='rounded-xl bg-gray-100 border border-gray-200 max-w-[65%] mx-auto my-5 p-2'>
      <div className=" flex gap-5 p-2">
          <div className="max-w-[40%]">
            <a>
              <img src="https://www.ibm.com/blog/wp-content/uploads/2023/09/dsc02281-edit-edit-5-edit.blog-lead-space-40x21-1.jpg" alt=""/>
            </a>
          </div>
          <div className='flex flex-col gap-5'>
            <a>
            <h1 className='font-bold text-3xl'>How ChatGPT and other AI tools can transform our world.</h1>
            </a>
            <p className="flex gap-5 items-center">
              <a className="font-semibold text-sm">Username</a>
              <time className='text-gray-500 text-xs font-semibold'>03-10-2024 , 00:00:00</time>
            </p>
            <p className="text-sm">We love A.I. and welcome you to our AI blog. There is so much going on in the field of AI and our goal is to keep you up-to-date in innovative, informative, and entertaining ways. We see this website as a form of digital art as all images and text were generated by artificial intelligence (with a little bit of human help).

            </p>
          </div>
      </div>
    </div>
   
  )
}

export default Post